Change icons (landing banner)
nus-gdg/nus-gdg.github.io pull request #26
Opened 2024-07-17 00:22 UTC by nknguyenhc

2024-07-20 06:44 UTC, Singa-pirate requested changes
LGTM except for the blurry svg issue on iPhone

2024-07-20 06:44 UTC, Singa-pirate commented on new/src/assets/images/landing.svg
Can consider exporting from figma as png / try different svg format.

The current svg does not render clearly on iPhone chrome:
![svg_iphone_chrome](https://github.com/user-attachments/assets/cf346f70-9b9e-42e3-a390-8fc05424028b)

For png:
![png_iphone_chrome](https://github.com/user-attachments/assets/8213c890-3f2c-45a5-85a8-c315ad9a9c10)

2024-07-21 06:44 UTC, nknguyenhc commented on new/src/assets/images/landing.svg
Changed to PNG

2024-07-21 11:09 UTC, Singa-pirate approved these changes
LGTM!

2024-07-21 15:27 UTC, merged